server.document-root="/var/www/html"
server.port=80
index-file.names = ( "index.php", "index.html" )

# Enable PHP
server.modules += ( "mod_fastcgi", "mod_rewrite" )
fastcgi.server = ( ".php" =>
  ((
    "socket" => "/var/run/php/php7-fpm.sock",
    "broken-scriptfilename" => "enable"
  ))
)
url.rewrite-if-not-file = (
  "^/(.*)$" => "/index.php/$1"
)


